server:
  port: 8090
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/postcard
    username: postgres
    password: postoat4
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
oat:
  app:
     jwtSecret: ======================OATSpring===========================
     jwtExpirationMs: 30000
     jwtCookieName: oatTest